#!/usr/bin/bash

OLD_PWD=$(pwd)
BASE_PATH=$(cd $(dirname "$0"); pwd)
NODE_PATH=$(which node)
SYSTEMD_PATH=/usr/lib/systemd/system

gen_systemd_unit () {
	cat <<-EOF
	[Unit]
	Description=Simple tool to handle services and webhook integrations.

	[Service]
	ExecStart=$NODE_PATH $BASE_PATH
	Restart=on-failure
	RestartSec=2

	[Install]
	WantedBy=multi-user.target
	EOF
}

if [ -d "${SYSTEMD_PATH}" ]; then
	"Creating systemd service.."
	echo "$(gen_systemd_unit)" > "$SYSTEMD_PATH/paddle.service"

	if [ -f "$BASE_PATH/local.js" ]; then
		systemctl start paddle
		systemctl --no-pager -n5 status paddle
	else
		[ -z "$CODERAFT" ] && echo "Provide a local.js"
	fi
fi

cd $OLD_PWD
